turtle_pi_joint_state_controller:
  # The joint state controller handles publishing transforms for any moving joints
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

wheel_joints:
  left_wheel_joint:
    speed_pid: [1002, 62, 2] 
    mode: position

  right_wheel_joint:
    speed_pid: [1002, 62, 2] 
    mode: position

